<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>TubeMailGorilla.CustomActions</AssemblyName>
    <RootNamespace>TubeMailGorilla.CustomActions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="CustomAction.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WixToolset.Dtf.CustomAction" Version="5.0.0" />
    <PackageReference Include="WixToolset.Dtf.WindowsInstaller" Version="5.0.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.IO.Compression" />
  </ItemGroup>
</Project>