param(
    [Parameter(Mandatory = $true)][string]$PublishDir,
    [Parameter(Mandatory = $true)][string]$OutFile
)

# Generates a WiX v4/v5+ source file harvesting every file under $PublishDir
# into components (auto-GUIDs), with a Start Menu shortcut, ready for:
#   wix build -arch x64 -o installer.msi <OutFile>

$ErrorActionPreference = 'Stop'
$PublishDir = (Resolve-Path $PublishDir).Path.TrimEnd('\')
$upgradeCode = 'B7E6A2C1-4F3D-4E8B-9A05-1C2D3E4F5A6B'

function Get-StableId([string]$prefix, [string]$key) {
    $san = ($key -replace '[^A-Za-z0-9_]', '_')
    if ($san.Length -gt 50) {
        $md5 = [System.Security.Cryptography.MD5]::Create()
        $hash = [BitConverter]::ToString($md5.ComputeHash([Text.Encoding]::UTF8.GetBytes($key))) -replace '-', ''
        $san = $san.Substring(0, 50) + '_' + $hash.Substring(0, 8)
    }
    return "$prefix$san"
}

# Skip the huge local LLM model - it is downloaded during installation instead
$allFiles = Get-ChildItem -LiteralPath $PublishDir -Recurse -File | Where-Object { $_.Extension -ne '.gguf' }

# Directories: relative path -> wix id
$dirIds = @{ '' = 'INSTALLFOLDER' }
foreach ($f in $allFiles) {
    $rel = $f.FullName.Substring($PublishDir.Length + 1)
    if ($rel -match '\\') {
        $parts = $rel.Substring(0, $rel.LastIndexOf('\')) -split '\\'
        $acc = ''
        foreach ($p in $parts) {
            $acc = if ($acc -eq '') { $p } else { "$acc\$p" }
            if (-not $dirIds.ContainsKey($acc)) {
                $dirIds[$acc] = Get-StableId 'Dir_' $acc
            }
        }
    }
}

# Group files per directory
$filesByDir = @{}
$componentIds = [System.Collections.Generic.List[string]]::new()
$bodyComponents = [System.Text.StringBuilder]::new()

foreach ($f in $allFiles) {
    $rel = $f.FullName.Substring($PublishDir.Length + 1)
    $relDir = ''; $fileName = $rel
    if ($rel -match '\\') {
        $relDir = $rel.Substring(0, $rel.LastIndexOf('\'))
        $fileName = $rel.Substring($rel.LastIndexOf('\') + 1)
    }
    $dirId = $dirIds[$relDir]
    $compId = Get-StableId 'Cmp_' $rel
    $fileId = Get-StableId 'Fil_' $rel
    $componentIds.Add($compId)

    if (-not $filesByDir.ContainsKey($dirId)) { $filesByDir[$dirId] = [System.Collections.Generic.List[string]]::new() }

    $srcEsc = $f.FullName -replace '&', '&amp;'
    $null = $bodyComponents.AppendLine("    <StandardDirectory Id=`"ProgramFiles64Folder`">") | Out-Null
    # placeholder; real emission happens below grouped by dir
    $filesByDir[$dirId].Add("      <Component Id=`"$compId`" Guid=`"*`">`n        <File Id=`"$fileId`" Name=`"$fileName`" Source=`"$srcEsc`" />`n      </Component>")
}

# Build nested directory tree XML under INSTALLFOLDER (children with their components)
function Emit-DirTree {
    param([System.Collections.Generic.List[string]]$PathParts, [System.Text.StringBuilder]$Out, [string]$Indent)
    $acc = ($PathParts -join '\')
    $dirId = $script:dirIds[$acc]
    $name = $PathParts[-1]
    $null = $Out.AppendLine("$Indent<Directory Id=`"$dirId`" Name=`"$name`">") | Out-Null
    if ($script:filesByDir.ContainsKey($dirId)) {
        foreach ($c in $script:filesByDir[$dirId]) { $null = $Out.AppendLine($c) | Out-Null }
    }
    # children = dirs whose parent path equals $acc
    $childMap = @{}
    foreach ($relDir in $script:dirIds.Keys) {
        if ($relDir -eq '') { continue }
        $parent = Split-Path $relDir -Parent
        if ($parent -eq $acc) { $childMap[$relDir] = $true }
    }
    foreach ($child in ($childMap.Keys | Sort-Object)) {
        Emit-DirTree -PathParts ([System.Collections.Generic.List[string]]($child -split '\\')) -Out $Out -Indent "$Indent    "
    }
    $null = $Out.AppendLine("$Indent</Directory>") | Out-Null
}

$subDirXml = [System.Text.StringBuilder]::new()
foreach ($top in ($dirIds.Keys | Where-Object { $_ -ne '' -and (Split-Path $_ -Parent) -eq '' } | Sort-Object)) {
    Emit-DirTree -PathParts ([System.Collections.Generic.List[string]]($top -split '\\')) -Out $subDirXml -Indent '        '
}
$dirXml = $subDirXml

# Root (INSTALLFOLDER) components
$rootXml = [System.Text.StringBuilder]::new()
if ($filesByDir.ContainsKey('INSTALLFOLDER')) {
    foreach ($c in $filesByDir['INSTALLFOLDER']) { $null = $rootXml.AppendLine($c) | Out-Null }
}

# Feature component refs
$refsXml = [System.Text.StringBuilder]::new()
foreach ($id in $componentIds) {
    $null = $refsXml.AppendLine("        <ComponentRef Id=`"$id`" />") | Out-Null
}

$caDll = Join-Path $PSScriptRoot '..\..\TubeMailGorilla.CustomActions\bin\Release\net472\TubeMailGorilla.CustomActions.CA.dll'
$caDll = [System.IO.Path]::GetFullPath($caDll)
$caEsc = $caDll -replace '&', '&amp;'

$doc = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by generate-harvest.ps1 - do not edit. -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="TubeMailGorilla" Manufacturer="TubeMailGorilla"
           Version="1.0.0" UpgradeCode="$upgradeCode"
           Scope="perMachine" Compressed="yes" InstallerVersion="500">

    <MajorUpgrade DowngradeErrorMessage="A newer version of TubeMailGorilla is already installed." />
    <MediaTemplate EmbedCab="yes" MaximumUncompressedMediaSize="4" />

    <Property Id="MODELDOWNLOADURL" Value="https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf" />

    <Binary Id="ModelDownloadCA" SourceFile="$caEsc" />
    <SetProperty Id="DownloadModelAction" Value="INSTALLFOLDER=[INSTALLFOLDER];MODELDOWNLOADURL=[MODELDOWNLOADURL]" Before="DownloadModelAction" Sequence="execute" />
    <CustomAction Id="DownloadModelAction" BinaryRef="ModelDownloadCA" DllEntry="DownloadLlamaModel" Execute="deferred" Impersonate="no" Return="check" />
    <InstallExecuteSequence>
      <Custom Action="DownloadModelAction" After="InstallFiles" Condition="NOT Installed" />
    </InstallExecuteSequence>

    <Feature Id="Main" Title="TubeMailGorilla" Description="TubeMailGorilla desktop application" Level="1">
        <ComponentRef Id="ShortcutComponent" />
$($refsXml)    </Feature>

    <StandardDirectory Id="ProgramFiles64Folder">
      <Directory Id="INSTALLFOLDER" Name="TubeMailGorilla">
$($rootXml)      </Directory>
$($dirXml)    </StandardDirectory>

    <StandardDirectory Id="ProgramMenuFolder">
      <Directory Id="AppMenuFolder" Name="TubeMailGorilla">
        <Component Id="ShortcutComponent" Guid="C1D2E3F4-A5B6-4C7D-8E9F-0A1B2C3D4E5F">
          <Shortcut Id="AppShortcut" Name="TubeMailGorilla"
                    Description="TubeMailGorilla - YouTube lead extraction"
                    Target="[INSTALLFOLDER]TubeMailGorilla.Maui.exe"
                    WorkingDirectory="INSTALLFOLDER" />
          <RemoveFolder Id="RemoveAppMenuFolder" Directory="AppMenuFolder" On="uninstall" />
          <RegistryValue Root="HKCU" Key="Software\TubeMailGorilla" Name="ShortcutInstalled"
                         Type="integer" Value="1" KeyPath="yes" />
        </Component>
      </Directory>
    </StandardDirectory>
  </Package>
</Wix>
"@

[System.IO.File]::WriteAllText($OutFile, $doc, [System.Text.UTF8Encoding]::new($false))
Write-Host "Harvested $($componentIds.Count) files across $($dirIds.Count) directories -> $OutFile"

